name: Sync Resume Folder from Repo B

on:
    workflow_dispatch: # Triggered by the workflow in Repo B

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Pull Resume Folder from Repo B
        env:
          TOKEN: ${{ secrets.RESUME }}
        run: |
          git clone 'https://shahviransh:${{env.TOKEN}}@github.com/shahviransh/McMaster-University.git'
          cd McMaster-University
          git sparse-checkout set Resume
          rsync -a Resume/Resume.pdf ../Resume.pdf
          cd ..
          rm -rf McMaster-University

      - name: Commit Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Resume.pdf
          git commit -m "Sync Resume folder from Repo B" || exit 0
          git push origin main
