name: Sync Resume Folder from Repo B

on:
  # Trigger on schedule (daily at midnight)
  schedule:
    - cron: '0 0 * * *'
  # Trigger on push to main branch of Repo B
  push:
    branches:
      - main
    paths:
      - 'McMaster-University/Resume/Resume.pdf' # Only trigger if Resume.pdf is changed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: shahviransh/McMaster-University
          token: ${{ secrets.RESUME }}

      - name: Copy Resume.pdf
        run: |
          cp McMaster-University/Resume/Resume.pdf Resume.pdf

      - name: Commit Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Resume.pdf
          git commit -m "Sync Resume folder from Repo B" || exit 0
          git push origin main
